version: '3'
services:
  api:
    container_name: payroll_api
    build: api-payroll/
    ports:
     - "8085:80"
    volumes:
     - .:/var/www/site
    depends_on:
      - mysql
  mysql:
    container_name: payroll_mysql
    restart: always
    image: mysql:8.0.12
    ports:
     - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_USER: 'sloth'
      MYSQL_PASS: '12345678'
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
