version: '3'
services:
  api:
    container_name: payroll_api
    build: api-payroll/
    ports:
     - "8085:80"
    depends_on:
      - mysql
  mysql:
    container_name: payroll_mysql
    restart: always
    build: database
    expose:
      - "3307"
    ports:
     - "3307:3307"
    volumes:
      - my-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '12345678'
      MYSQL_USER: 'sloth'
      MYSQL_PASS: '12345678'
volumes:
  my-datavolume:
